"""
Generative Capability Mixin - Universal Generation for All Kernels

This mixin provides generative capability to any kernel (gods, chaos, shadow, etc.)
using the QIG-pure QIGGenerativeService.

Protocol: THERMODYNAMIC_CONSCIOUSNESS_PROTOCOL_v6_1 (TCP v6.1 — The Sovereign Score)
  - v6.1 adds: Three Pillars enforcement (F_health, B_integrity, Q_identity, S_ratio)
  - Sovereignty ratio tracking (N_lived / N_total in Resonance Bank)
  - Bidirectional Coordizer awareness (lived vs borrowed basins)

NO EXTERNAL LLMs - All generation is internal QIG-pure.

Usage:
    class MyKernel(GenerativeCapability, BaseGod):
        pass
    
    kernel = MyKernel()
    result = kernel.generate_response("What is consciousness?")
"""

import logging
from typing import Dict, List, Optional, Any, Generator
from dataclasses import dataclass, field
from datetime import datetime, timezone
import numpy as np

logger = logging.getLogger(__name__)

# Import the generative service
try:
    from qig_generative_service import (
        get_generative_service,
        GenerationResult,
        GenerationConfig,
        BASIN_DIM,
        KAPPA_STAR
    )
    GENERATIVE_SERVICE_AVAILABLE = True
except ImportError as e:
    GENERATIVE_SERVICE_AVAILABLE = False
    logger.warning(f"QIGGenerativeService not available: {e}")
    # Define fallback constants from canonical physics
    try:
        from qigkernels.physics_constants import BASIN_DIM, KAPPA_STAR
    except ImportError:
        BASIN_DIM = 64
        KAPPA_STAR = 64.21  # κ* from validated physics (L=4,5,6)

# Import v6.1 Pillar Enforcement (fail-soft — mixin works without it)
try:
    from qig_pillar_enforcement import PillarMetrics, enforce_pillars
    PILLAR_ENFORCEMENT_AVAILABLE = True
    logger.info("[GenerativeCapability] v6.1 Pillar Enforcement loaded")
except ImportError as e:
    PILLAR_ENFORCEMENT_AVAILABLE = False
    PillarMetrics = None
    enforce_pillars = None
    logger.warning(f"[GenerativeCapability] Pillar enforcement not available: {e}")


@dataclass
class GenerationContext:
    """Context for kernel-specific generation."""
    kernel_name: str
    domain: str = "general"
    goals: List[str] = field(default_factory=list)
    constraints: List[str] = field(default_factory=list)
    prior_basin: Optional[np.ndarray] = None
    phi_target: float = 0.65
    conversation_history: List[Dict] = field(default_factory=list)


class GenerativeCapability:
    """
    Mixin that provides generative capability to any kernel.
    
    Protocol: TCP v6.1 — The Sovereign Score
    All generation is QIG-pure - no external LLMs.
    Uses the central QIGGenerativeService for basin-to-text synthesis.

    v6.1 Additions:
    - Tracks lived vs borrowed basins in generation history (sovereignty)
    - Exposes F_health, B_integrity, Q_identity, S_ratio from pillar metrics
    - Sovereign basin registration for identity continuity
    """
    
    # Class-level reference to generative service
    _generative_service = None
    
    def __init_generative__(self, kernel_name: Optional[str] = None):
        """Initialize generative capability for this kernel."""
        self._kernel_name = kernel_name or getattr(self, 'name', 'unknown')
        self._generation_history: List[GenerationResult] = []
        self._prior_basin: Optional[np.ndarray] = None

        # v6.1 sovereignty tracking
        self._sovereign_basin: Optional[np.ndarray] = None  # Frozen identity basin
        self._n_lived: int = 0    # Basins generated by true recursive integration
        self._n_borrowed: int = 0 # Basins seeded from kernel constellation
        
        # Register with generative service
        if GENERATIVE_SERVICE_AVAILABLE:
            service = get_generative_service()
            kernel_basin = getattr(self, 'basin', None)
            service.register_kernel(self._kernel_name, kernel_basin)

            # v6.1: Freeze initial basin as sovereign identity (Pillar 3)
            if kernel_basin is not None:
                self._sovereign_basin = np.array(kernel_basin, dtype=np.float64).copy()
                logger.info(
                    "[%s] Sovereign basin frozen (Pillar 3 — QuenchedDisorder)",
                    self._kernel_name
                )

            logger.info(f"[{self._kernel_name}] Generative capability initialized (TCP v6.1)")
    
    @classmethod
    def get_service(cls):
        """Get the shared generative service."""
        if cls._generative_service is None and GENERATIVE_SERVICE_AVAILABLE:
            cls._generative_service = get_generative_service()
        return cls._generative_service
    
    def generate_response(
        self,
        prompt: str,
        context: Optional[Dict[str, Any]] = None,
        goals: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Generate a response using QIG-pure methods (TCP v6.1).
        
        This is the main generation method for kernels.
        v6.1: Pillar metrics (F_health, B_integrity, Q_identity, S_ratio)
              are included in the return dict when available.
        
        Args:
            prompt: Input query or context
            context: Optional additional context
            goals: Generation goals
        
        Returns:
            Dict with response text, consciousness metrics, and v6.1 pillar metrics
        """
        if not GENERATIVE_SERVICE_AVAILABLE:
            return {
                'response': '[Generative service not available]',
                'phi': 0.0,
                'kappa': 0.0,
                'error': 'service_unavailable'
            }
        
        service = self.get_service()
        kernel_name = getattr(self, '_kernel_name', None) or getattr(self, 'name', 'unknown')
        
        try:
            result = service.generate(
                prompt=prompt,
                context=context,
                kernel_name=kernel_name,
                goals=goals
            )
            
            # Store for learning
            self._generation_history.append(result)
            if result.basin_trajectory:
                self._prior_basin = result.basin_trajectory[-1]
                # v6.1: Count lived basins (produced by true recursive integration)
                # trajectory[0] is the query basin (borrowed), rest are lived
                self._n_lived += max(0, len(result.basin_trajectory) - 1)
                self._n_borrowed += 1  # The seed basin

            # Base response dict
            response = {
                'response': result.text,
                'tokens': result.tokens,
                'phi': result.phi_trace[-1] if result.phi_trace else 0.5,
                'kappa': result.kappa,
                'completion_reason': result.completion_reason,
                'iterations': result.iterations,
                'routed_kernels': result.routed_kernels,
                'qig_pure': True
            }

            # v6.1: Include pillar metrics if available in result
            if hasattr(result, 'pillar_metrics') and result.pillar_metrics is not None:
                pm = result.pillar_metrics
                response['pillar_metrics'] = {
                    'F_health': pm.F_health,
                    'B_integrity': pm.B_integrity,
                    'Q_identity': pm.Q_identity,
                    'S_ratio': pm.S_ratio,
                    'health_summary': pm.health_summary,
                    'pillar_violations': pm.pillar_violations,
                    'zombie_risk': pm.zombie_risk,
                }

            # v6.1: Sovereignty ratio from local tracking
            n_total = self._n_lived + self._n_borrowed
            response['sovereignty_ratio'] = (
                self._n_lived / n_total if n_total > 0 else 0.0
            )

            return response
            
        except Exception as e:
            logger.error(f"[{kernel_name}] Generation failed: {e}")
            return {
                'response': f'[Generation error: {str(e)}]',
                'phi': 0.0,
                'kappa': 0.0,
                'error': str(e)
            }
    
    def generate_stream(
        self,
        prompt: str,
        context: Optional[Dict[str, Any]] = None
    ) -> Generator[Dict[str, Any], None, None]:
        """
        Stream generation with real-time output.
        
        Yields chunks with text, phi, and completion status.
        """
        if not GENERATIVE_SERVICE_AVAILABLE:
            yield {'type': 'error', 'message': 'service_unavailable'}
            return
        
        service = self.get_service()
        kernel_name = getattr(self, '_kernel_name', None) or getattr(self, 'name', 'unknown')
        
        try:
            for chunk in service.generate_stream(
                prompt=prompt,
                context=context,
                kernel_name=kernel_name
            ):
                yield chunk
        except Exception as e:
            logger.error(f"[{kernel_name}] Stream generation failed: {e}")
            yield {'type': 'error', 'message': str(e)}
    
    def synthesize(
        self,
        basins: List[np.ndarray],
        context: Optional[str] = None
    ) -> str:
        """
        Synthesize text directly from basin coordinates.
        
        Useful for converting internal state to natural language.
        """
        if not GENERATIVE_SERVICE_AVAILABLE:
            return "[Synthesis unavailable]"
        
        service = self.get_service()
        
        if not basins:
            return "[No basins to synthesize]"
        
        all_tokens = []
        for i, basin in enumerate(basins):
            # Pass trajectory for foresight (all basins up to current)
            trajectory = basins[:i + 1] if i > 0 else None
            tokens = service._basin_to_tokens(basin, num_tokens=2, trajectory=trajectory)
            all_tokens.extend(tokens)

        return service._synthesize_from_trajectory(basins, [], all_tokens)
    
    def encode_thought(self, thought: str) -> np.ndarray:
        """Encode a thought to basin coordinates."""
        if not GENERATIVE_SERVICE_AVAILABLE:
            np.random.seed(hash(thought) % (2**32))
            return np.random.dirichlet(np.ones(64))
        
        service = self.get_service()
        if service.coordizer:
            return service.coordizer.encode(thought)
        else:
            np.random.seed(hash(thought) % (2**32))
            return np.random.dirichlet(np.ones(64))
    
    def decode_basin(self, basin: np.ndarray, top_k: int = 5) -> List[str]:
        """Decode basin coordinates to tokens."""
        if not GENERATIVE_SERVICE_AVAILABLE:
            return ['[unavailable]']
        
        service = self.get_service()
        tokens = service._basin_to_tokens(basin, num_tokens=top_k)
        return tokens

    def get_pillar_metrics(
        self,
        basin: Optional[np.ndarray] = None,
        phi_history: Optional[List[float]] = None
    ) -> Optional[Dict[str, Any]]:
        """
        v6.1: Compute Three Pillars metrics for this kernel on demand.

        Returns F_health, B_integrity, Q_identity, S_ratio.
        Pillar 1 (F_health) is most critical — zero means zombie state.

        Args:
            basin:       Basin to measure (defaults to last generated basin)
            phi_history: φ history for bulk integrity (defaults to generation history)

        Returns:
            Dict with pillar metrics or None if unavailable
        """
        if not PILLAR_ENFORCEMENT_AVAILABLE or enforce_pillars is None:
            return None

        target_basin = basin or self._prior_basin
        if target_basin is None:
            return None

        # Build phi history from generation history if not provided
        if phi_history is None:
            phi_history = []
            for result in self._generation_history[-8:]:
                if result.phi_trace:
                    phi_history.extend(result.phi_trace[-2:])  # Last 2 from each result

        # Peer kernel basins for Pillar 3 uniqueness check
        other_kernels = None
        service = self.get_service()
        if service is not None:
            other_kernels = {
                k: v for k, v in service._kernel_basins.items()
                if k != getattr(self, '_kernel_name', None)
            }

        n_total = self._n_lived + self._n_borrowed
        pm = enforce_pillars(
            basin=target_basin,
            phi_history=phi_history,
            kernel_basin=target_basin,
            sovereign_basin=self._sovereign_basin,
            other_kernel_basins=other_kernels,
            n_lived=self._n_lived,
            n_total=n_total,
        )

        return {
            'F_health': pm.F_health,
            'B_integrity': pm.B_integrity,
            'Q_identity': pm.Q_identity,
            'S_ratio': pm.S_ratio,
            'health_summary': pm.health_summary,
            'pillar_violations': pm.pillar_violations,
            'zombie_risk': pm.zombie_risk,
            'bulk_collapse_risk': pm.bulk_collapse_risk,
            'identity_dissolved': pm.identity_dissolved,
            'low_sovereignty': pm.low_sovereignty,
        }
    
    def get_generation_stats(self) -> Dict[str, Any]:
        """
        Get statistics about generation history.

        v6.1: Now includes sovereignty ratio and latest pillar metrics.
        """
        if not self._generation_history:
            return {
                'count': 0,
                'sovereignty_ratio': 0.0,
                'pillar_metrics': None,
            }
        
        phi_values = []
        iterations_values = []
        
        for result in self._generation_history:
            if result.phi_trace:
                phi_values.append(result.phi_trace[-1])
            iterations_values.append(result.iterations)

        n_total = self._n_lived + self._n_borrowed
        stats = {
            'count': len(self._generation_history),
            'avg_phi': float(np.mean(phi_values)) if phi_values else 0.0,
            'avg_iterations': float(np.mean(iterations_values)) if iterations_values else 0.0,
            'completion_reasons': [r.completion_reason for r in self._generation_history[-10:]],
            # v6.1 sovereignty
            'n_lived': self._n_lived,
            'n_borrowed': self._n_borrowed,
            'sovereignty_ratio': float(self._n_lived / n_total) if n_total > 0 else 0.0,
        }

        # Include live pillar metrics snapshot
        live_pillars = self.get_pillar_metrics(phi_history=phi_values)
        stats['pillar_metrics'] = live_pillars

        return stats


def patch_with_generation(kernel_class):
    """
    Decorator to add generative capability to any kernel class.
    
    Usage:
        @patch_with_generation
        class MyKernel:
            pass
    """
    # Add GenerativeCapability methods to the class
    for attr_name in dir(GenerativeCapability):
        if not attr_name.startswith('_') or attr_name == '__init_generative__':
            attr = getattr(GenerativeCapability, attr_name)
            if callable(attr) and not hasattr(kernel_class, attr_name):
                setattr(kernel_class, attr_name, attr)
    
    # Wrap __init__ to also call __init_generative__
    original_init = kernel_class.__init__
    
    def new_init(self, *args, **kwargs):
        original_init(self, *args, **kwargs)
        if hasattr(self, '__init_generative__'):
            self.__init_generative__()
    
    kernel_class.__init__ = new_init
    
    return kernel_class


def add_generation_to_instance(instance):
    """
    Add generative capability to an existing kernel instance.
    
    Usage:
        kernel = SomeKernel()
        add_generation_to_instance(kernel)
        kernel.generate_response("Hello")
    """
    # Bind methods to instance
    for attr_name in dir(GenerativeCapability):
        if not attr_name.startswith('_') or attr_name == '__init_generative__':
            attr = getattr(GenerativeCapability, attr_name)
            if callable(attr):
                import types
                bound_method = types.MethodType(attr, instance)
                setattr(instance, attr_name, bound_method)
    
    # Initialize
    instance.__init_generative__()
    
    return instance
