// All phrases use ONLY BIP-39 wordlist words (validated)
// Themes: Bitcoin/crypto 2009, cypherpunk philosophy, Mac aesthetic
// Validated thematic words: balance, basic, build, change, citizen, clean, code, control,
// digital, elegant, empower, future, limit, network, own, permit, power, private, proof,
// protect, public, rule, safe, secret, simple, smooth, supply, system, trust, truth, zero

export const KNOWN_12_WORD_PHRASES = [
  "proof system trust network digital code private public truth safe balance simple",
  "future supply limit protect empower citizen digital network code trust balance truth",
  "simple elegant design smooth clean basic balance truth empower future digital system",
  "trust network replace allow permit control safe protect empower citizen digital truth",
  "digital network system build protect private truth safe balance simple proof future",
  "code network digital system proof truth safe protect balance simple elegant trust",
  "private network public code system digital proof safe trust balance truth future",
  "protect empower citizen digital system network simple truth balance proof code safe",
  "balance supply limit protect digital network system truth simple elegant code future",
  "truth network digital code proof system protect balance simple trust future supply",
  "safe system digital network code proof private balance truth simple elegant protect",
  "simple system elegant clean basic smooth balance digital network code truth future",
  "network digital system trust proof code safe protect balance simple truth supply",
  "empower citizen digital network protect private code system truth balance proof simple",
  "digital system network proof code truth safe balance protect simple elegant future",
  "trust digital network system code proof safe truth balance simple protect supply",
  "code digital system network proof safe truth protect balance simple trust future",
  "protect digital network system safe truth balance simple code proof trust supply",
  "balance digital network system truth proof safe protect simple elegant code future",
  "simple digital network system elegant proof truth safe balance protect code trust",
  "future digital network system supply limit protect truth balance simple elegant code",
  "truth digital network code proof system safe balance protect simple trust future",
  "safe digital network system proof code truth balance protect simple elegant trust",
  "network digital system code proof truth safe protect balance simple elegant future",
  "digital network code system proof safe truth balance protect simple trust supply",
  "proof digital network system code safe truth balance protect simple elegant future",
  "system digital network proof code safe truth balance protect simple elegant trust",
  "empower digital network citizen protect system code truth balance proof simple future",
  "protect digital network citizen empower system code truth balance simple elegant proof",
  "balance network digital system proof safe truth protect simple elegant code future",
  "simple network digital system proof elegant truth safe balance protect code trust",
  "elegant network digital system simple proof truth safe balance protect code future",
  "trust network digital code system proof safe balance protect simple truth future",
  "safe network digital code system proof truth balance protect simple elegant trust",
  "digital code network system proof safe truth balance protect simple elegant future",
  "code network digital proof system safe truth balance protect simple elegant trust",
  "proof network digital code system safe truth balance protect simple elegant future",
  "network code digital system proof safe truth balance protect simple elegant trust",
  "system code digital network proof safe truth balance protect simple elegant future",
  "truth code digital network system proof safe balance protect simple elegant future",
  "protect code digital network system proof safe truth balance simple elegant trust",
  "balance code digital network system proof safe truth protect simple elegant future",
  "simple code digital network system proof elegant truth safe balance protect trust",
  "elegant code digital network system simple proof truth safe balance protect future",
  "future code digital network system supply limit truth protect balance simple elegant",
];
