/**
 * SHARED TYPES - Centralized Exports
 * 
 * TypeScript types shared between client and server.
 * Import from '@shared/types' for all shared type definitions.
 * 
 * Note: Some types are re-exported in multiple files for backwards compatibility.
 * This barrel file explicitly exports to avoid conflicts.
 */

// Branded types (primary source for Phi, Kappa, Beta, etc.)
export {
  type Phi,
  type Kappa,
  type Beta,
  type BasinCoordinate,
  type EraTimestamp,
  type GeodesicDistance,
  type BasinCoordinates64,
  type TypedConsciousnessSignature,
  createPhi,
  createKappa,
  createBeta,
  createBasinCoordinate,
  createGeodesicDistance,
  createEraTimestamp,
  createBasinCoordinates64,
  clampPhi,
  clampKappa,
  clampBasinCoordinate,
  isValidPhi,
  isValidKappa,
  isValidBasinCoordinate,
  isValidEraTimestamp,
  toTypedSignature,
  avgPhi,
  avgKappa,
  lerpPhi,
  lerpKappa,
  BrandedTypeError,
} from './branded';

// Core types (primary source for address types, validation, etc.)
export {
  RegimeType,
  type Regime,
  regimeSchema,
  AddressType,
  type AddressTypeValue,
  addressTypeSchema,
  bitcoinAddressSchema,
  type BitcoinAddress,
  privateKeyHexSchema,
  type PrivateKeyHex,
  wifSchema,
  type WIF,
} from './core';

// QIG geometry types
export {
  type BasinCoordinates,
  type ConsciousnessMetrics,
  type FisherMetric,
  type KernelState,
  type ConstellationState,
  type QIGScore,
  type SearchEvent,
  type FrontendEvent,
  type NaturalGradient,
  basinCoordinatesSchema,
  consciousnessMetricsSchema,
  fisherMetricSchema,
  kernelStateSchema,
  constellationStateSchema,
  qigScoreSchema,
  searchEventSchema,
  frontendEventSchema,
  naturalGradientSchema,
  regimeTypeSchema,
  E8_CONSTANTS,
  METRIC_DEFINITIONS,
  checkConsciousness,
  fisherRaoDistance,
  qigGeometrySchemas,
} from './qig-geometry';

// Olympus Pantheon types
export {
  type GodDomain,
  type GodAssessment,
  type ConvergenceType,
  type ConvergenceInfo,
  type PollResult,
  type WarMode,
  type ZeusAssessment,
  type WarDeclaration,
  type WarEnded,
  type GodStatus,
  type OlympusStatus,
  type ObservationContext,
  type GodName,
  type KernelMode,
  type GodType,
  type GodMetadata,
  type GodProfile,
  type OrchestrationResult,
  type PantheonStatus,
  type GodsResponse,
  type ConstellationResult,
  type NearestGodsResult,
  type GodSimilarityResult,
  GodDomainSchema,
  GodAssessmentSchema,
  ConvergenceTypeSchema,
  ConvergenceInfoSchema,
  PollResultSchema,
  WarModeSchema,
  ZeusAssessmentSchema,
  WarDeclarationSchema,
  WarEndedSchema,
  GodStatusSchema,
  OlympusStatusSchema,
  ObservationContextSchema,
  GodNameSchema,
  olympusSchemas,
  OrchestrationResult,
  OrchestrationResultSchema,
  PantheonHypothesis,
  PantheonHypothesisSchema,
} from './olympus';
