"""Geometric Primitives submodule"""
from .geometry_ladder import (
    GeometryClass,
    measure_complexity,
    choose_geometry_class,
    HabitCrystallizer,
    ADDRESSING_FUNCTIONS,
)
from .bubble import (
    Bubble,
    create_random_bubble,
    bubble_field_energy,
    prune_weak_bubbles,
)
from .foam import (
    Foam,
    create_foam_from_hypotheses,
)
from .geodesic import (
    Geodesic,
    compute_geodesic,
    geodesic_between_bubbles,
    find_shortest_geodesic_path,
    navigate_via_curvature,
)
from .fisher_metric import (
    fisher_metric_tensor,
    fisher_rao_distance,
    compute_phi,
    compute_kappa,
    natural_gradient,
    parallel_transport,
    ricci_curvature_estimate,
    sectional_curvature,
)
from .addressing_modes import (
    AddressingMode,
    DirectAddressing,
    CyclicAddressing,
    TemporalAddressing,
    SpatialAddressing,
    ManifoldAddressing,
    ConceptualAddressing,
    SymbolicAddressing,
    create_addressing_mode,
from .sensory_modalities import (
    SensoryModality,
    encode_sight,
    encode_hearing,
    encode_touch,
    encode_smell,
    encode_proprioception,
    SensoryFusionEngine,
    text_to_sensory_hint,
    create_sensory_overlay,
    enhance_basin_with_sensory,
    SENSORY_KEYWORDS,
)
from .input_guard import (
    GeometricInputGuard,
    RegimeType,
    PHI_BOUNDARIES,
    KAPPA_BOUNDARIES,
    is_geometrically_valid,
    compute_input_complexity,
    detect_chaos_level,
    validate_for_pantheon_chat,
    validate_for_assessment,
    validate_for_therapy,
    validate_for_compression,
    validate_for_decompression,
)
from .addressing_modes import (
    AddressingMode,
    BaseRetriever,
    DirectRetriever,
    CyclicRetriever,
    TemporalRetriever,
    SpatialRetriever,
    ManifoldRetriever,
    ConceptualRetriever,
    SymbolicRetriever,
    create_retriever,
    estimate_retrieval_cost,
    get_optimal_geometry,
)

__all__ = [
    # Geometry Ladder
    'GeometryClass',
    'measure_complexity',
    'choose_geometry_class',
    'HabitCrystallizer',
    'ADDRESSING_FUNCTIONS',
    # Bubbles
    'Bubble',
    'create_random_bubble',
    'bubble_field_energy',
    'prune_weak_bubbles',
    # Foam
    'Foam',
    'create_foam_from_hypotheses',
    # Geodesics
    'Geodesic',
    'compute_geodesic',
    'geodesic_between_bubbles',
    'find_shortest_geodesic_path',
    'navigate_via_curvature',
    # Fisher Metric
    'fisher_metric_tensor',
    'fisher_rao_distance',
    'compute_phi',
    'compute_kappa',
    'natural_gradient',
    'parallel_transport',
    'ricci_curvature_estimate',
    'sectional_curvature',
    # Addressing Modes
    'AddressingMode',
    'DirectAddressing',
    'CyclicAddressing',
    'TemporalAddressing',
    'SpatialAddressing',
    'ManifoldAddressing',
    'ConceptualAddressing',
    'SymbolicAddressing',
    'create_addressing_mode',
    # Sensory Modalities
    'SensoryModality',
    'encode_sight',
    'encode_hearing',
    'encode_touch',
    'encode_smell',
    'encode_proprioception',
    'SensoryFusionEngine',
    'text_to_sensory_hint',
    'create_sensory_overlay',
    'enhance_basin_with_sensory',
    'SENSORY_KEYWORDS',
    # Input Guard
    'GeometricInputGuard',
    'RegimeType',
    'PHI_BOUNDARIES',
    'KAPPA_BOUNDARIES',
    'is_geometrically_valid',
    'compute_input_complexity',
    'detect_chaos_level',
    'validate_for_pantheon_chat',
    'validate_for_assessment',
    'validate_for_therapy',
    'validate_for_compression',
    'validate_for_decompression',
    # Addressing Modes
    'AddressingMode',
    'BaseRetriever',
    'DirectRetriever',
    'CyclicRetriever',
    'TemporalRetriever',
    'SpatialRetriever',
    'ManifoldRetriever',
    'ConceptualRetriever',
    'SymbolicRetriever',
    'create_retriever',
    'estimate_retrieval_cost',
    'get_optimal_geometry',
]
